version: "3.8"

services:
  server:
    image: yakrajpariyar/ujiyala-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    restart: always
